### ISSUE TITLE
Null pointer exception 

### ISSUE THREAD

**Issue by MatiasVara** [gemoc/modelanimation#2]
Hi, 

I have just found a problem in: 
"gemoc.execution.engine.ui/src/org/gemoc/execution/engine/debug/AbstractGemocDebugger.java:68"

The code is: 

bundleSymbolicName = getBundleSymbolicName(getLanguageDefinition(engine.getExecutionContext().getLanguageDefinitionExtension().getXDSMLFilePath()));

The line does not check if getLanguageDefinitionExtension() returns null, which is the case for GemocCoordinatedDebuger. I fixed it by simply adding an "if" before: 

if (engine.getExecutionContext().getLanguageDefinitionExtension() != null) {
        bundleSymbolicName = getBundleSymbolicName(getLanguageDefinition(engine.getExecutionContext().getLanguageDefinitionExtension().getXDSMLFilePath()));
}

So far, the Gemoc Coordinated debug works well. However, I am not sure if it is the correct solution. Should I commit and push the changes? 

Matias

**Comment by dvojtise** [comment]
Hi 
you can push your solution with a comment explaining that xdsml may not be required for coordination engine

An even better solution would be to split the AbstractGemocDebugger, and have one dedicated to AbstractGemocXDSMLDebugger which requires an xdsml and the AbstractGemocDebugger the part in common for all debuggers including the coordination one.

**Comment by MatiasVara** [comment]
Thanks a lot, I will go for the first solution for the moment. 

Matias
